### ISSUE TITLE
Conversion deprecation warning with PHP 8.1

### ISSUE THREAD

**Issue by UweKeim** [katzgrau/KLogger#102]
When upgrading my project to PHP 8.1, I get tons of these warnings:

> Deprecated: Implicit conversion from float 1641216285.352105 to int loses precision in C:\MyProject\vendor\katzgrau\klogger\src\Logger.php on line 308

Looking at the source code, this is the excerpt:

```php
296: /**
297:  * Gets the correctly formatted Date/Time for the log entry.
299:  *
299:  * PHP DateTime is dump, and you have to resort to trickery to get microseconds
300:  * to work correctly, so here it is.
301:  *
302:  * @return string
303:  */
304: private function getTimestamp()
305: {
306:     $originalTime = microtime(true);
307:     $micro = sprintf("%06d", ($originalTime - floor($originalTime)) * 1000000);
308:     $date = new DateTime(date('Y-m-d H:i:s.'.$micro, $originalTime));
309:
310:     return $date->format($this->options['dateFormat']);
311: }
```

So the error occurs in [this line 308](https://github.com/katzgrau/KLogger/blob/de2d3ab6777a393a9879e0496ebb8e0644066e3f/src/Logger.php#L308):

```php
$date = new DateTime(date('Y-m-d H:i:s.'.$micro, $originalTime));
```

### My question

Are you planning to update your library to work without the warning?

If not, any other suggestions on how to resolve this by myself?

-----------

### Update 1

I do think the issue is that in line 306,  the [call to `microtime()`](https://www.php.net/manual/en/function.microtime.php) returns a `float`, which in turn is passed as the `$timestamp` parameter in line 308 to the [`date()` call](https://www.php.net/manual/en/function.date.php) which required the `$timestamp` parameter to be an `int`.

In my tests, the deprecation warning went away, when explicitly casting to `int`, e.g.:

```php
$date = new DateTime(date('Y-m-d H:i:s.'.$micro, (int)$originalTime));
```

Here, I casted `$originalTime` to `int`.

[See e.g. this blog article for more details](https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string).

**Comment by kamilwylegala** [comment]
@UweKeim I also get many deprecation notices after upgrade to PHP 8.1.

@katzgrau Would you accept an pull request with fix?

**Comment by katzgrau** [comment]
Hi @kamilwylegala , thanks for the suggestion — sure thing, submit it and I'll have a look

**Comment by kamilwylegala** [comment]
Here is pull request, thanks in advance: https://github.com/katzgrau/KLogger/pull/103

**Comment by UweKeim** [comment]
Still no progress on this 😭.

**Comment by katzgrau** [comment]
Ha, sorry @UweKeim — merged in #103

**Comment by UweKeim** [comment]
Thank you so much, @katzgrau.

Any chance that it also appears on https://packagist.org/packages/katzgrau/klogger in the near future, please?

**Comment by katzgrau** [comment]
Yep, all set @UweKeim
