### ISSUE TITLE
KLogger class initialization

### ISSUE THREAD

**Issue by tragicrock** [katzgrau/KLogger#13]
Would probably be good to add the following to your KLogger.php file:

if (!class_exists('KLogger')) {
    class KLogger
    {
        ...
    }
}

I only say this b/c otherwise you have to wrap every include / require with the check.  Since this is a logging class, by it's definition it will likely be called / instantiated many times in page builds with errors / notices in them.

Just a thought.  Thanks for all the work you've done on it regardless.

John

**Comment by katzgrau** [comment]
Thanks for the suggestion! I know in some projects it's a habit (like Wordpress), but I'll leave this out mainly because I'd rather the user know about potential multiple includes, etc.

Sorry for the time warp :)
