### ISSUE TITLE
Specific Log Name in constructor

### ISSUE THREAD

**Issue by mbutomax** [katzgrau/KLogger#23]
Wouldn't be useful to give the opportunity to choose the name file in the constructor?
Maybe this simple yet powerful log engine could be used more than one time in a project. Naming a log is something very important in some environments. And there is often a naming convention to follow.

**Comment by katzgrau** [comment]
Okay, okay. I'll add this.

**Comment by katzgrau** [comment]
PS, w

**Comment by katzgrau** [comment]
https://github.com/katzgrau/KLogger/commit/42461f1c7c7e286a9cd0d9aa1fc7b2d269f932c0
