### ISSUE TITLE
[feature] optional JSON output

### ISSUE THREAD

**Issue by Ultrabenosaurus** [katzgrau/KLogger#35]
While the current format is certainly human-readable, and from the description and code KLogger certainly seems like a good tool, I think it could be helpful to add a toggle for JSON output. This would greatly aid users who want machine-readable logs, the main use-case I can think of would be a web dashboard with an area that lets you search and filter logs to for reading.

It could be a simple toggle between human- and machine-readable formats, or possible a setting to duplicate logging between the two.

**Comment by katzgrau** [comment]
Interesting - let me think about it
