### ISSUE TITLE
Support setting log line format

### ISSUE THREAD

**Issue by katzgrau** [katzgrau/KLogger#39]
Provide a way to set the format that a log line is written

**Comment by onno-vos-dev** [comment]
@katzgrau What is your idea with this? I'm willing to help out but would like to have a pointer what it is that you're looking for :)

**Comment by katzgrau** [comment]
@richjenks is having a look, but in general, being able to supply a template for the log lines inside the file. It would give the user more flexibility to make the logs readable, machine readable, etc
```php
// Example
$logger = new Katzgrau\KLogger\Logger('/var/log/', Psr\Log\LogLevel::WARNING, array (
    'format' => "[date]\t[level]\t[message]", // changes the log file extension
));
```

**Comment by onno-vos-dev** [comment]
Cool, let me know if you'd like me to help out on it as well.

I don't want to start commenting on a closed issue, but perhaps we could include issue #35 in this issue in that case? 

wdyt @katzgrau ?

(I would like to help out expand KLogger seeing as I make use of it on a daily basis, I wanna return the favor! :+1: )

**Comment by katzgrau** [comment]
Thanks!

Let's let @richjenks implement the shortcode-style of specifying a format, and then if you're interested, maybe implement a shortcode such as `[json]` to specify json output?

**Comment by richjenks** [comment]
Can this be closed in light of https://github.com/katzgrau/KLogger/pull/54?

**Comment by katzgrau** [comment]
Yep
