### ISSUE TITLE
Extension, filename and prefix not applying

### ISSUE THREAD

**Issue by tleb** [katzgrau/KLogger#48]
Hello,

for some reason, the extension, filename and prefix settings do not apply.

```
$ composer clearcache
$ mkdir test
$ cd test
$ composer require katzgrau/klogger
$ touch index.php
```

In `index.php`:

```php
<?php

require 'vendor/autoload.php';

$logger = new Katzgrau\KLogger\Logger(__DIR__, Psr\Log\LogLevel::DEBUG, array (
    'extension' => 'log'
));
$logger->error('error content');
```

It creates the log file, but in standard format `log_2015-04-09.txt`. Any explanation? Is it linked to my environment, so that I am the only one to have this issue?

**Comment by onno-vos-dev** [comment]
You're using the outdated Katzgrau when you pull it in like that.

Use: composer require katzgrau/klogger:dev-master

instead to pull in the latest master branch. Then your code runs fine and I'm getting the correct fileformat :)

**Comment by tleb** [comment]
Sad it's not written anywhere. Even the README recommends using `composer require katzgrau/klogger:1.0.*`, which would lead to the same problem.

Why is it not 1.0.1 ?

**Comment by onno-vos-dev** [comment]
I just opened an issue for this :)

**Comment by tleb** [comment]
Works now. :smile: Am I the first one to fall into this? Oo

**Comment by onno-vos-dev** [comment]
Nope, @drasive fell for this as well as can be seen in https://github.com/katzgrau/KLogger/issues/46
