### ISSUE TITLE
Update ReadMe to have composer install dev-master

### ISSUE THREAD

**Issue by onno-vos-dev** [katzgrau/KLogger#49]
The ReadMe and Composer.json should be updated to state that that dev-master should be pulled instead. 

Alternatively, version 1.0.0 on composer should fetch the latest master. 

See: https://github.com/katzgrau/KLogger/issues/48

**Comment by onno-vos-dev** [comment]
@katzgrau Want me to submit a PR? I'm quite swamped today and tomorrow but I can submit a PR on the weekend if you'd like.

**Comment by katzgrau** [comment]
Thanks! Will hit this up tomorrow AM (yes, repeat of the last PR comment :) )
