### ISSUE TITLE
If filename is provided, we should check if an extension is provided in the filename

### ISSUE THREAD

**Issue by onno-vos-dev** [katzgrau/KLogger#50]
Currently on Line 124 of Logger.php we check if the filename is provided. If so, we accept the filename as is without adding or checking for an extension. 
```` 
if ($this->options['filename']) {
                $this->logFilePath = $logDirectory.DIRECTORY_SEPARATOR.$this->options['filename'];
            }
```` 

I suggest we do an additional check if the extension is provided as well. If not, the default logfile name should be chosen instead. This to prevent users from being able to add a filename and "expecting the default logextension" to be added to this but instead receive a filename without extension which could be problematic.

**Comment by onno-vos-dev** [comment]
@katzgrau I can submit a PR on the weekend for this so you can leave this for me.

**Comment by katzgrau** [comment]
Thanks! Will hit this up tomorrow AM
