### ISSUE TITLE
New release for Packagist sourcing

### ISSUE THREAD

**Issue by TeslaDethray** [katzgrau/KLogger#71]
Sorry to bug you again!

I am wondering if it would be possible to make a new release of KLogger so that I can pull the source down on Packagist, please. Right now, users trying to install our package get an error message because we've sourced KLogger on dev-master, and (as I had forgotten) our minimum-stability is too high for that.

https://github.com/pantheon-systems/cli/issues/622

**Comment by katzgrau** [comment]
Done - 1.2.0

**Comment by TeslaDethray** [comment]
Thank you so much!
