### ISSUE TITLE
disable logging while leaving methods in place

### ISSUE THREAD

**Issue by tobsn** [katzgrau/KLogger#76]
Is there any way to turn off logging completely?
I want to turn it on/off depending on environment.

currently I'm handling it this way:

    $this->log = new Katzgrau\KLogger\Logger(
        __DIR__.'/logs',
        (
            ( getenv('APP_ENV') == 'production' )
            ? Psr\Log\LogLevel::EMERGENCY
            : Psr\Log\LogLevel::DEBUG
        )
    );

**Comment by katzgrau** [comment]
There used to be a log level named ::OFF, but since we switched to implementing the PSR class it went away.

Adding an enable($bool) method to disable logging would probably be a decent idea, although I'd probably imagine you really would want EMERGENCY errors in any environment, right?

**Comment by tobsn** [comment]
well... it's deployed to elastic beanstalk so textfile logging is pretty useless since it would happen on any of many servers - error handling is done via bugsnag so that's sorta taken care of. I use it purely locally and on staging (one server) which is why I wanted a nice log file but all that should be silent on production. technically the emergency workaround would work since I only use debug(), notice() etc.

honestly maybe it's not even needed... since the log level kinda takes care of it.


(btw. if you know any other way to locally nicely debug... logging is all I came up with so far since it's an API and a worker (no interface, fed by queue))

**Comment by katzgrau** [comment]
There's always xdebug and ChromePHP - found them both pretty useful in the past: http://xdebug.org/

As for the second param - we're just following the logger interface: https://github.com/php-fig/log/blob/master/Psr/Log/AbstractLogger.php
