### ISSUE TITLE
Class Logger not found

### ISSUE THREAD

**Issue by martinjinda** [katzgrau/KLogger#77]
Hi guys,

I've just install KLogger via composer and I set the same options as in **Basic Usage** and I've got this error. 
`Fatal error: Class 'Katzgrau\KLogger\Logger' not found`

If I try require just `Logger.php` from `src`. I've got an error:
`Fatal error: Class 'Psr\Log\AbstractLogger' not found`

**Comment by tleb** [comment]
Hello,

Have you required the composer autoloader?

```php
require(__DIR__ . '/vendor/autoload.php');
```

**Comment by katzgrau** [comment]
Closing since it's not a KLogger issue, just composer usage issue
