### ISSUE TITLE
Non-Composer instructions

### ISSUE THREAD

**Issue by dscherertfm** [katzgrau/KLogger#81]
Please provide a dependency list for those of us not using composer.

**Comment by onno-vos-dev** [comment]
It's next to impossible to provide you with a dependency list. How come you're not using composer yet? It's trivial to run composer... Once composer has built the directory structure you're free to copy this directory into your application if you must avoid using composer...

**Comment by katzgrau** [comment]
Use a pre-1.0.0 release: https://github.com/katzgrau/KLogger/releases

Package management is just the reality of modern web-dev - you're probably wasting quite a bit of your time if you choose not to use it. Asking any project to list dependency chains is clearly impractical (and if you disagree, you're taking it up with the wrong people).

**Comment by dscherertfm** [comment]
I've gone 10+ years without Composer and haven't had a need for it yet. Seems like a lot of overhead to write/learn configuration files and whatnot to do what I can do with a mouse and a keyboard in a couple seconds most of the time. Plus the one time I did try to use composer the autoloader screwed with the autoloading for the application.

**Comment by dscherertfm** [comment]
It's impractical to list dependency chains? Oh dear....

**Comment by onno-vos-dev** [comment]
I don't want ant to buy  either harsh but times are changing. Composer Ansbach other package managers are simply a fact of life nowadays. 

If composer screwed with your autoloader you're probably doing something wrong.

**Comment by katzgrau** [comment]
Fine, but web development will continue to move forward regardless of whether you need to use modern tools. At some point, you're making your knowledge/skillset obsolete.

**Comment by dscherertfm** [comment]
Times are certainly changing, and I'm sure people have found package management convenient. Regardless I'd rather not be blind to dependencies. I also sincerely doubt that my avoiding package managers is going to make my ability to continue to write modern software obsolete.

**Comment by katzgrau** [comment]
Ok, agree to disagree. I really can't spend any more time on this — please open an issue with literally any other npm/rubygem/apt/yum/composer package repo and ask them for the dependency chain.
